export const readTime = (content: string) => Math.ceil(content.length / 500)
export const langMap: Record<string, string> = {
  javascript: "javascript",
  python: "python",
  cpp: "cpp",
  java: "java",
  "c programming": "c",
  "c-programming": "c",
  c: "c",
  "c++": "cpp",
  "c#": "csharp",
  csharp: "csharp",
  go: "go",
  rust: "rust",
  php: "php",
  ruby: "rb",
  swift: "swift",
  kotlin: "kt",
  scala: "scala",
  typescript: "ts",
  html: "html",
  nodejs: "js",
}

export const extMap: Record<string, string> = {
  javascript: "js",
  python: "py",
  cpp: "cpp",
  java: "java",
  "c programming": "c",
  "c-programming": "c",
  c: "c",
  csharp: "cs",
  go: "go",
  rust: "rs",
  php: "php",
  rb: "rb",
  swift: "swift",
  kt: "kt",
  scala: "scala",
  ts: "ts",
  html: "html",
  js: "js",
}
